// <auto-generated />
using System;
using IdleRPG.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdleRPG.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615073052_AddSetBonuses")]
    partial class AddSetBonuses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IdleRPG.Domain.Entities.AntiBotEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("ActionTaken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("action_taken");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("EventType")
                        .HasColumnType("smallint")
                        .HasColumnName("event_type");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json")
                        .HasDefaultValueSql("'{}'");

                    b.Property<int>("NewScore")
                        .HasColumnType("integer")
                        .HasColumnName("new_score");

                    b.Property<int>("RiskDelta")
                        .HasColumnType("integer")
                        .HasColumnName("risk_delta");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_anti_bot_events");

                    b.HasIndex("UserId", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_antibot_user_created");

                    b.ToTable("anti_bot_events", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Class")
                        .HasColumnType("smallint")
                        .HasColumnName("class");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<long>("Experience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("experience");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("name");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<string>("StatsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("stats_json")
                        .HasDefaultValueSql("'{}'");

                    b.Property<short>("TeamSlot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)0)
                        .HasColumnName("team_slot");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_characters_user_id")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("characters", null, t =>
                        {
                            t.HasCheckConstraint("ck_characters_level", "level BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("ck_characters_team_slot", "team_slot BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("BaseRarity")
                        .HasColumnType("smallint")
                        .HasColumnName("base_rarity");

                    b.Property<string>("BaseStatsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("base_stats_json")
                        .HasDefaultValueSql("'{}'");

                    b.Property<short?>("CharacterRestriction")
                        .HasColumnType("smallint")
                        .HasColumnName("character_restriction");

                    b.Property<short>("Class")
                        .HasColumnType("smallint")
                        .HasColumnName("class");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSeasonal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_seasonal");

                    b.Property<bool>("IsTradeable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_tradeable");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unique");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("PassivesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("passives_json")
                        .HasDefaultValueSql("'[]'");

                    b.Property<Guid?>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<short>("Slot")
                        .HasColumnType("smallint")
                        .HasColumnName("slot");

                    b.Property<string>("SteamMarketHashName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("steam_market_hash_name");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_items_name");

                    b.HasIndex("SetId")
                        .HasDatabaseName("ix_items_set_id");

                    b.HasIndex("SteamMarketHashName")
                        .IsUnique()
                        .HasDatabaseName("ix_items_steam_market_hash_name");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.ItemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcquiredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short?>("EquippedSlot")
                        .HasColumnType("smallint")
                        .HasColumnName("equipped_slot");

                    b.Property<Guid?>("EquippedToCharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipped_to_character_id");

                    b.Property<bool>("IsListedOnMarket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_listed_on_market");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<DateTimeOffset?>("LastSteamValidation")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_steam_validation");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<short>("RolledRarity")
                        .HasColumnType("smallint")
                        .HasColumnName("rolled_rarity");

                    b.Property<string>("RolledStatsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("rolled_stats_json")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("SteamInventoryId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("steam_inventory_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_item_instances");

                    b.HasIndex("EquippedToCharacterId")
                        .HasDatabaseName("ix_item_instances_equipped_to_character_id");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_item_instances_item_id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("idx_item_instances_owner");

                    b.HasIndex("SteamInventoryId")
                        .IsUnique()
                        .HasDatabaseName("idx_item_instances_steam");

                    b.ToTable("item_instances", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.SetBonus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("PiecesRequired")
                        .HasColumnType("smallint")
                        .HasColumnName("pieces_required");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<string>("StatBonusesJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("stat_bonuses_json")
                        .HasDefaultValueSql("'{}'");

                    b.HasKey("Id")
                        .HasName("pk_items_set_bonuses");

                    b.HasIndex("SetId", "PiecesRequired")
                        .IsUnique()
                        .HasDatabaseName("ix_items_set_bonuses_set_id_pieces_required");

                    b.ToTable("items_set_bonuses", null, t =>
                        {
                            t.HasCheckConstraint("ck_items_set_bonuses_pieces", "pieces_required >= 1");
                        });
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccountLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("account_level");

                    b.Property<int>("AntiBotRiskScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("risk_score");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<string>("BanReason")
                        .HasColumnType("text")
                        .HasColumnName("ban_reason");

                    b.Property<DateTimeOffset?>("BannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<DateTimeOffset>("LastLoginAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("status");

                    b.Property<string>("SteamId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("steam_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("SteamId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_steam_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_account_level", "account_level >= 1");

                            t.HasCheckConstraint("ck_users_risk_score", "risk_score BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.AntiBotEvent", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_anti_bot_events_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Character", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_characters_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.ItemInstance", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.Character", "EquippedToCharacter")
                        .WithMany("EquippedItems")
                        .HasForeignKey("EquippedToCharacterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_item_instances_characters_equipped_to_character_id");

                    b.HasOne("IdleRPG.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_item_instances_items_item_id");

                    b.HasOne("IdleRPG.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_instances_users_owner_id");

                    b.Navigation("EquippedToCharacter");

                    b.Navigation("Item");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("IdleRPG.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.Character", b =>
                {
                    b.Navigation("EquippedItems");
                });

            modelBuilder.Entity("IdleRPG.Domain.Entities.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
